services:
  web:
    build: .
    container_name: symfony_web
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - db
    networks:
      - symfony_network

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_DATABASE: dicrawler
      MYSQL_ROOT_PASSWORD: 1203
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge