<div class="col-lg-12">
    <h1 class="page-header">Crawlerkonfigurationen</h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->type ?>-Crawler
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTable no-footer" id="crawlerConfig">
                        <thead>
                        <tr>
                            <td>Unternehmens-ID</td>
                            <td>Unternehmensname</td>
                            <td>Pfad</td>
                            <td>Verhalten</td>
                            <td>Cron</td>
                            <td>Laufzeit</td>
                            <td>Status</td>
                            <td>Autor</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        /* @var $eCrawlerConfig Marktjagd_Database_Entity_CrawlerConfig */
                        foreach ($this->cConfig as $eCrawlerConfig): ?>
                            <tr onclick="window.location='/Crawler/crawler/crawlerdetail/idCrawlerConfig/<?php
                                    echo $eCrawlerConfig->getIdCrawlerConfig() ?>'"
                                style ="cursor:pointer;">
                                <td><?php echo $eCrawlerConfig->getIdCompany() ?></td>
                                <td><?php echo $eCrawlerConfig->getCompany()->getName() ?></td>
                                <td><?php echo $eCrawlerConfig->getFileName() ?></td>
                                <td><?php echo $eCrawlerConfig->getCrawlerBehaviour()->getBehaviour() ?></td>
                                <td><?php echo $eCrawlerConfig->getExecution() ?></td>
                                <td><?php echo $eCrawlerConfig->getRuntime() ?></td>
                                <td><?php echo $eCrawlerConfig->getCrawlerStatus() ?></td>
                                <td><?php echo $eCrawlerConfig->getAuthor()->getFirstName() . ' '
                                        . $eCrawlerConfig->getAuthor()->getLastName() ?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#crawlerConfig').dataTable({
            "oLanguage": {
                "sProcessing":   "Bitte warten...",
                "sLengthMenu": "Zeige _MENU_ Einträge pro Seite",
                "sZeroRecords": "Nichts gefunden. Entschuldigung",
                "sInfo": "Zeige _START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "Zeige 0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert aus allen _MAX_ Einträgen)",
                "sInfoPostFix":  "",
                "sSearch":       "Suchen",
                "sUrl":          "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            },
            "fnPreDrawCallback": function(oSettings, json) {
                $('.dataTables_filter input').addClass('form-control input-sm');
                $('.dataTables_filter input').css('width', '200px');
                $('.dataTables_length select').addClass('form-control input-sm');
                $('.dataTables_length select').css('width', '75px');
            }
        } );
    } );
</script>