<div class="col-lg-12">
    <h1 class="page-header">DI-Dashboard</h1>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Vergleich  Artikel-, Prospekt- & Standort-Crawler
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="crawler_type"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Anzahl geschriebener Crawler pro Person
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="crawler_authors"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Vergleich alte Crawler - neue Crawler
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="crawler_versions"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>
<div class="row">
    <div class="col-lg-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div style="float:left;"><i class="fa fa-coffee fa-fw"></i> Instabile Crawler in den letzten x Monaten</div>
                <div style="height: 26px; float:right; margin: -3px;"><?php echo $this->formCrawlerInstable ?></div>
                <div style="clear:both; height: 0;">&nbsp;</div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover dataTable no-footer" id="instableCrawler">
                    <thead>
                        <td>Crawler</td>
                        <td>Anzahl erfolgreich</td>
                        <td>Anzahl fehlerhaft</td>
                        <td>Fehlerquote in %</td>
                    </thead>
                    <tbody>
                    <?php
                        $userInfo = Zend_Auth::getInstance()->getStorage()->read();

                        foreach ($this->aCrawlerInstable as $idCrawlerConfig => $crawler) : ?>
                            <tr onclick="window.location='/Crawler/crawler/crawlerdetail/idCrawlerConfig/<?php
                                echo $idCrawlerConfig . '/userLevel/' . $userInfo->role['level']?>'" style ="cursor:pointer;">
                                <td><?php echo $crawler['name'] . ' ' . ucwords($crawler['type']) . '-Crawler'?></td>
                                <td><?php echo $crawler['success']?></td>
                                <td><?php echo $crawler['failed']?></td>
                                <td><?php echo number_format((float) ($crawler['failureRate']*100), 2, '.', '') ?></td>
                            </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>

    <div class="col-lg-5">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bell fa-fw"></i> Letzte fehlgeschlagene Crawler
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="list-group">
                    <?php
                    $status = array(
                        3 => 'Crawler fehlgeschlagen',
                        5 => 'Crawler konnte nicht gestartet werden',
                        7 => 'Import anlegen fehlgeschlagen',
                        9 => 'Import fehlerhaft');

                    foreach ($this->cFinished as $elementFinished):
                        /* @var $elementFinished Marktjagd_Database_Entity_CrawlerLog */

                        $icon = 'fa fa-bolt fa-fw';
                        if ($elementFinished->getIdCrawlerLogType() >= 7) {
                            $icon = 'fa fa-warning fa-fw';
                        }
                        ?>
                        <a href="<?php echo $this->_baseUrl . '/Crawler/logging/detail/idCrawlerLog/'
                                            . $elementFinished->getIdCrawlerLog() ?>" class="list-group-item">
                            <i class="<?php echo $icon ?>"></i> <?php
                            echo $elementFinished->getCrawlerConfig()->getCompany()->getName()
                                 . ' (ID: ' . $elementFinished->getCrawlerConfig()->getCompany()->getIdCompany() . '): '
                                 . $status[$elementFinished->getIdCrawlerLogType()]
                            ?>
                            <span class="pull-right text-muted small"><em><?php
                                    $timeEnd = $elementFinished->getImportEnd(true);

                                    if (!$timeEnd
                                        || !($timeEnd)
                                    ) {
                                        $timeEnd = $elementFinished->getEnd(true);
                                    }

                                    $timeEnd = new DateTime($timeEnd);
                                    $interval = $timeEnd->diff(new DateTime());

                                    echo 'vor '
                                         . ($interval->d!=0?$interval->d . ' Tage(n) ':'')
                                         . ($interval->h!=0?$interval->h . ' Stunde(n) ':'')
                                         . ($interval->i . ' Minute(n)');?></em>
                                    </span>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>
<div class="row">
    <div class="col-lg-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Angelegte / Modifizierte Crawler
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="crawler_modified"></div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>

<script type="text/javascript">
    Morris.Donut({
        element: 'crawler_authors',
        data: [
        <?php
            foreach ($this->aUserCrawlerCount as $user => $count):
                echo '{label: "' . $user . '", value: ' . $count . '},';
            endforeach;
        ?>
        ]
    });

    Morris.Donut({
        element: 'crawler_versions',
        data: [
            <?php
                foreach ($this->aCrawlerVersionCount as $version => $count):
                    echo '{label: "' . $version . '", value: ' . $count . '},';
                endforeach;
            ?>
        ]
    });

    Morris.Donut({
        element: 'crawler_type',
        data: [
            <?php
                foreach ($this->aCrawlerTypeCount as $type => $count):
                    echo '{label: "' . $type . '", value: ' . $count . '},';
                endforeach;
            ?>
        ]
    });

    Morris.Area({
        element: 'crawler_modified',
        data: [
            <?php
                foreach ($this->aCrawlerModifiedCount as $month => $aCount):
                    echo '{y: "' . $month . '", '
                        . 'a: ' . $aCount['articles'] . ', '
                        . 'b: ' . $aCount['brochures'] . ', '
                        . 'c: ' . $aCount['stores'] . '},';
                endforeach;
            ?>
        ],
        xkey: 'y',
        ykeys: ['a', 'b', 'c'],
        labels: ['Angelegte / Geänderte Artikelcrawler', 'Angelegte / Geänderte Prospektcrawler', 'Angelegte / Geänderte Standortcrawler']
    });

    $(document).ready(function() {
        $('#instableCrawler').dataTable({
            "oLanguage": {
                "sProcessing":   "Bitte warten...",
                "sLengthMenu": "Zeige _MENU_ Einträge pro Seite",
                "sZeroRecords": "Nichts gefunden. Entschuldigung",
                "sInfo": "Zeige _START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "Zeige 0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert aus allen _MAX_ Einträgen)",
                "sInfoPostFix":  "",
                "sSearch":       "Suchen",
                "sUrl":          "",
                "oPaginate": {
                    "sFirst":    "Erster",
                    "sPrevious": "Zurück",
                    "sNext":     "Nächster",
                    "sLast":     "Letzter"
                }
            },
            "aaSorting": [],
            "fnPreDrawCallback": function(oSettings, json) {
                $('.dataTables_filter input').addClass('form-control input-sm');
                $('.dataTables_filter input').css('width', '200px');
                $('.dataTables_length select').addClass('form-control input-sm');
                $('.dataTables_length select').css('width', '75px');
            }
        } );
    } );
</script>
