# config/services.yaml

services:
    # Default configuration for services
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $ftpServer: '%env(FTP_SERVER)%'
            string $ftpUsername: '%env(FTP_USERNAME)%'
            string $ftpPassword: '%env(FTP_PASSWORD)%'
            int $ftpPort: '%env(int:FTP_PORT)%'

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Register FtpService
    App\Service\FtpService:
        arguments:
            $ftpServer: '%env(FTP_SERVER)%'
            $ftpUsername: '%env(FTP_USERNAME)%'
            $ftpPassword: '%env(FTP_PASSWORD)%'
            $ftpPort: '%env(int:FTP_PORT)%'
