<!DOCTYPE html>
<html>
<head>
    <title>data integration</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <?php echo $this->headMeta(); ?>
    <!-- jQuery und jQueryUI -->
    <link rel="stylesheet" href="/css/cupertino/jquery-ui-1.11.0.min.css">
    <link rel="stylesheet" href="/css/cupertino/jquery-ui-theme-1.11.0.css">
    <script type="text/javascript" src="/js/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui-1.11.0.min.js"></script>

    <!-- Twitter Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>

    <!-- JS Datatables -->
    <script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript" src="/js/datatables.js"></script>
    <link rel="stylesheet" href="/css/dataTables.bootstrap.css">

    <!-- SB Admin Template -->
    <link href="/css/sb-admin.css" rel="stylesheet">
    <script src="/js/sb-admin.js"></script>

    <!-- Menüplugin -->
    <script src="/js/jquery.metisMenu.js"></script>

    <!-- Diagramme -->
    <link href="/css/morris.css" rel="stylesheet">
    <script src="/js/morris.js"></script>
    <script src="/js/raphael-2.1.0.min.js"></script>


    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/font-awesome/css/font-awesome.min.css">

    <!-- Eigenes CSS -->
    <link rel="stylesheet" href="/css/custom.css">

    <!-- Eigenes Javascript -->
    <script type="text/javascript" src="/js/custom.js"></script>
</head>
<body>
<?php
$userInfo = Zend_Auth::getInstance()->getStorage()->read();
if ($userInfo):
    $urlStore = '/Crawler/crawler/store';
    $urlArticle = '/Crawler/crawler/article';
    $urlBrochure = '/Crawler/crawler/brochure';
    $urlRetailer = '/Crawler/crawler/retailer';
    $upcomingCrawler = '/Crawler/logging/index';
    $finishedCrawler = '/Crawler/logging/finished';
    $addCrawler = '/Crawler/crawler/crawleradd';
    $updateCompany = '/Crawler/index/updatecrawler';
    $convertMjGoogle = '/Google/index/mjtogooglecsv';
    $convertGoogleMj = '/Google/index/googlecsvtomj';
    $convertPdfToImages = '/Google/index/pdftoimages';
    $addFtp = '/Ftp/action/add';
    $showFtp = '/Ftp/action/show';
    $task = '/Task/index/show';
    $urlDetails = '/Overview/companydetail/detail';
    $urlErrors = '/Overview/companydetail/errors';
    $urlOverview = '/Overview/companydetail';
    $urlDetailOverview = '/Overview/companydetail/detailoverview';
    $urlMarketingInfos = '/Overview/companydetail/marketing';
    $urlOverviewConfig = '/Overview/companydetail/config';
    $urlAdSummary = '/Overview/advertising';
    $urlBrochureMods = '/BrochureMods/clickouts/comment';
    $uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); ?>

    <div id="wrapper">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?php echo $this->_baseUrl . '/' ?>">GUI DI v5.1.0</a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw" title="<?php echo $userInfo->userName ?>"></i>
                        <?php echo $userInfo->realName . ' (' . $userInfo->role['name'] . ')' ?>
                        <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <?php if ($userInfo->role['level'] == 0) : ?>
                            <li>
                                <a href="<?php echo $this->_baseUrl . '/Login/user/show' ?>"><i
                                            class="fa fa-cogs fa-fw"></i> Administration</a>
                            </li>
                        <?php endif; ?>
                        <li>
                            <a href="<?php echo $this->_baseUrl . '/Login/auth/logout/' ?>"><i
                                        class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
            </ul>
            <div class="navbar-default navbar-static-side" role="navigation">
                <ul class="nav" id="side-menu">
                    <li<?php echo $uri == $urlStore || $uri == $urlArticle || $uri == $urlBrochure || $uri == $updateCompany || $uri == $addCrawler ? ' class="active"' : '' ?>>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i>Crawler configurations
                            <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <?php if ($userInfo->role['level'] == 0) : ?>
                                <li><a href="<?php echo $addCrawler ?>"><i class="fa fa-sign-in fa-fw"></i>Create crawler</a></li>
                                <li><a href="<?php echo $updateCompany ?>"><i class="fa fa-refresh fa-fw"></i>Update companies</a></li>
                                <hr style="margin: 5px 0px 5px 0px;"/>
                            <?php endif; ?>
                            <li><a href="<?php echo $urlStore ?>"><i
                                            class="fa fa-hospital-o fa-fw"></i>Store crawlers</a></li>
                            <li><a href="<?php echo $urlArticle ?>"><i class="fa fa-apple fa-fw"></i>Article crawlers</a>
                            </li>
                            <li><a href="<?php echo $urlBrochure ?>"><i class="fa fa-file fa-fw"></i>Brochure crawlers</a>
                            </li>
                        </ul>
                    </li>
                    <li<?php echo $uri == $upcomingCrawler || $uri == $finishedCrawler ? ' class="active"' : '' ?>>
                        <a href="#"><i class="fa fa-files-o fa-fw"></i> Crawler overview<span
                                    class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="<?php echo $upcomingCrawler ?>"><i class="fa fa-spinner fa-fw"></i>Running/scheduled crawlers</a></li>
                            <li><a href="<?php echo $finishedCrawler ?>"><i class="fa fa-check fa-fw"></i>Finished crawlers</a></li>
                        </ul>
                    </li>
                    <?php if ($userInfo->role['level'] == 0) : ?>
                        <li<?php echo substr($uri, 0, strlen($addFtp)) == $addFtp || substr($uri, 0, strlen($showFtp)) == $showFtp ? ' class="active"' : '' ?>>
                            <a href="#"><i class="fa fa-upload fa-fw"></i> FTP<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="<?php echo $showFtp ?>"><i
                                                class="fa fa-users fa-fw"></i> User overview</a></li>
                                <li><a href="<?php echo $addFtp ?>"><i class="fa fa-folder-o fa-fw"></i> Create FTP access</a></li>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <?php if ($userInfo->role['level'] <= 50) : ?>
                        <li<?php echo $uri == $urlBrochureMods ? ' class="active"' : '' ?>>
                            <a href="#"><i class="fa fa-table fa-fw"></i>PDF editing<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="<?php echo $urlBrochureMods ?>"><i class="fa fa-google-plus fa-fw"></i> Clickout exchange</a>
                                </li>
                            </ul>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </nav>
        <div id="page-wrapper" style="min-height: 0px;">
            <div class="row"><?php echo $this->layout()->content; ?></div>
        </div>
    </div>
<?php else: ?>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please log in!</h3>
                    </div>
                    <div class="panel-body">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
</body>
</html>