<div class="col-lg-12">
    <h1 class="page-header">Übersicht</h1>
</div>
<div class="col-lg-12"><?php echo $this->overviewForm ?></div>
<?php if (is_array($this->aStores)) : $aMonths = array('3', '3', '1', '1', '1')?>
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Anzahl Produkte, Prospekte und Standorte</h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover dataTable no-footer" id="companyOverview">
                    <thead>
                        <tr>
                            <th>Unternehmens-ID</th>
                            <th>Unternehmens-Name</th>
                            <th>Anzahl Produkte</th>
                            <th>Letztes Update Produkte</th>
                            <th>Letzter Import Produkte</th>
                            <th>Anzahl Prospekte</th>
                            <th>Letztes Update Prospekte</th>
                            <th>Letzter Import Prospekte</th>
                            <th>Anzahl Standorte</th>
                            <th>Letztes Update Standorte</th>
                            <th>Letzter Import Standorte</th>
                        </tr>
                    </thead>
                    <?php foreach ($this->aStores as $singleStore): if (is_object($singleStore->getCompany())) : ?>
                        <tr>
                            <td><?php echo $singleStore->getCompany()->getIdCompany()?></td>
                            <td><?php echo $singleStore->getCompany()->getName()?></td>
                            <td<?php echo is_array($this->aProducts[$singleStore->getCompany()->getIdCompany()]) ? $this->aProducts[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aProducts[$singleStore->getCompany()->getIdCompany()])))] ? ' bgcolor="#E50054"' : '' : ''?>>
                                <?php echo !is_null($this->aProducts[$singleStore->getCompany()->getIdCompany()]) ? $this->aProducts[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aProducts[$singleStore->getCompany()->getIdCompany()])))] : '0' ?></td>
                            <td<?php echo !is_null($this->aProducts[$singleStore->getCompany()->getIdCompany()]['#lastTimeModified']) ?
                             $this->aProducts[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aProducts[$singleStore->getCompany()->getIdCompany()])))] != 0 ?
                                    strtotime($this->aProducts[$singleStore->getCompany()->getIdCompany()]['#lastTimeModified']) < strtotime('-' . $aMonths[$this->productId] . 'month') ? ' bgcolor="#E50054"' : '' : '' : ''
                            ?>>
                                    <?php
                                    echo !is_null($this->aProducts[$singleStore->getCompany()->getIdCompany()]['#lastTimeModified']) ? $this->aProducts[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aProducts[$singleStore->getCompany()->getIdCompany()])))] != 0 ?
                                            date('d.m.Y H:i', strtotime($this->aProducts[$singleStore->getCompany()->getIdCompany()]['#lastTimeModified'])) : '' : ''
                                    ?></td>
                            <td<?php echo !is_null($this->aProducts[$singleStore->getCompany()->getIdCompany()]['#lastImport']) ?
                             $this->aProducts[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aProducts[$singleStore->getCompany()->getIdCompany()])))] != 0 ?
                                    strtotime($this->aProducts[$singleStore->getCompany()->getIdCompany()]['#lastImport']) < strtotime('-' . $aMonths[$this->productId] . 'month') ? ' bgcolor="#E50054"' : '' : '' : ''
                            ?>><?php
                                    echo !is_null($this->aProducts[$singleStore->getCompany()->getIdCompany()]['#lastImport']) ? $this->aProducts[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aProducts[$singleStore->getCompany()->getIdCompany()])))] != 0 ?
                                            date('d.m.Y H:i', strtotime($this->aProducts[$singleStore->getCompany()->getIdCompany()]['#lastImport'])) : '' : ''
                                    ?></td>
                            <td<?php echo is_array($this->aBrochures[$singleStore->getCompany()->getIdCompany()]) ? $this->aBrochures[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aBrochures[$singleStore->getCompany()->getIdCompany()])))] ? ' bgcolor="#E50054"' : '' : ''?>>
                            <?php echo !is_null($this->aBrochures[$singleStore->getCompany()->getIdCompany()]) ? $this->aBrochures[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aBrochures[$singleStore->getCompany()->getIdCompany()])))] : '0' ?></td>
                            <td<?php
                            echo !is_null($this->aBrochures[$singleStore->getCompany()->getIdCompany()]['#lastTimeModified']) ? $this->aBrochures[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aBrochures[$singleStore->getCompany()->getIdCompany()])))] != 0 ?
                                    strtotime($this->aBrochures[$singleStore->getCompany()->getIdCompany()]['#lastTimeModified']) < strtotime('-' . $aMonths[$this->productId] . 'month') ? ' bgcolor="#E50054"' : '' : '' : ''
                            ?>>
                                    <?php
                                echo !is_null($this->aBrochures[$singleStore->getCompany()->getIdCompany()]['#lastTimeModified']) ? $this->aBrochures[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aBrochures[$singleStore->getCompany()->getIdCompany()])))] != 0 ?
                                        date('d.m.Y H:i', strtotime($this->aBrochures[$singleStore->getCompany()->getIdCompany()]['#lastTimeModified'])) : '' : ''
                                ?></td>
                            <td<?php
                            echo !is_null($this->aBrochures[$singleStore->getCompany()->getIdCompany()]['#lastImport']) ? $this->aBrochures[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aBrochures[$singleStore->getCompany()->getIdCompany()])))] != 0 ?
                                    strtotime($this->aBrochures[$singleStore->getCompany()->getIdCompany()]['#lastImport']) < strtotime('-' . $aMonths[$this->productId] . 'month') ? ' bgcolor="#E50054"' : '' : '' : ''
                            ?>><?php
                                echo !is_null($this->aBrochures[$singleStore->getCompany()->getIdCompany()]['#lastImport']) ? $this->aBrochures[$singleStore->getCompany()->getIdCompany()][(end(array_keys($this->aBrochures[$singleStore->getCompany()->getIdCompany()])))] != 0 ?
                                        date('d.m.Y H:i', strtotime($this->aBrochures[$singleStore->getCompany()->getIdCompany()]['#lastImport'])) : '' : ''
                                ?></td>
                            <td<?php echo $singleStore->getAmountStores() == 0 ? ' bgcolor="#E50054"' : '' ?>>
                                <?php echo $singleStore->getAmountStores() ?></td>
                            <td<?php echo $singleStore->getAmountStores() != 0 ? strtotime($singleStore->getLastTimeModified()) < strtotime('-' . $aMonths[$this->productId] . 'month') ? ' bgcolor="#E50054"' : '' : ''
                        ?>>
                        <?php echo $singleStore->getAmountStores() != 0 ? date('d.m.Y H:i', strtotime($singleStore->getLastTimeModified())) : '' ?></td>
                            <td><?php echo !is_null($singleStore->getLastImport()) ? date('d.m.Y H:i', strtotime($singleStore->getLastImport())) : '' ?></td>
                        </tr>
    <?php endif; endforeach; ?>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('#companyOverview').dataTable({
            "oLanguage": {
                "sProcessing": "Bitte warten...",
                "sLengthMenu": "Zeige _MENU_ Einträge pro Seite",
                "sZeroRecords": "Nichts gefunden. Entschuldigung",
                "sInfo": "Zeige _START_ bis _END_ von _TOTAL_ Einträgen",
                "sInfoEmpty": "Zeige 0 bis 0 von 0 Einträgen",
                "sInfoFiltered": "(gefiltert aus allen _MAX_ Einträgen)",
                "sInfoPostFix": "",
                "sSearch": "Suchen",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "Erster",
                    "sPrevious": "Zurück",
                    "sNext": "Nächster",
                    "sLast": "Letzter"
                }
            }
        });
    });
</script>