<h2 class="page-header">
    Standort Infos
</h2>
<div class="panel-body">
    <?php echo $this->marketingForm ?>
</div>
<h3 class="page-header">
    Wie viel % der Standorte werden mit Werbematerial abgedeckt?
</h3>
<div class="panel-body">
    <?php echo $this->assignmentForm ?>
</div>

<h3 class="page-header">
    Ermittlung ausgewählter Unternehmensstandorte innerhalb eines spezifischen Radius um andere Unternehmen
</h3>
<div class="panel-body">
    <?php echo $this->calculateDistanceForm ?>
</div>