<h1 class="page-header">Prospektbearbeitung</h1>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Kommentare in Prospekten umwandeln</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form; ?>
            </div>
        </div>
    </div>
</div>